title: Thalia Huynh # your name (or website title) here
logo: "/images/IMG_2943.JPG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data professional with 8+ years of public health and medical research experience looking to use data for social good.
  <br><br>
  Passionate about mental health + well-being and interested in how data can better improve the health of individuals and communities.
  <br><br>
  ğŸ’» Languages: Python, R, SAS, SQL<br>
  ğŸ“ Education:<br>
  Statistics, MS | CSU East Bay<br>
  Microbiology, BS | UC Davis<br>
  ğŸ“ Location: Bay Area, California<br>
  ğŸ˜„ Hobbies: photography, working out, reading, hiking, snowboarding
  <br><br>
  <a href="https://www.linkedin.com/in/thalia-huynh//">View My LinkedIn Profile</a>
  <a href="https://medium.com/@thaliahuynh//">View My Medium Blog</a> 
  
theme: jekyll-theme-minimal
